import * as React from "react";
import { GridProps, SwitchFieldProps, TextFieldProps } from "@aws-amplify/ui-react";
export declare type EscapeHatchProps = {
    [elementHierarchy: string]: Record<string, unknown>;
} | null;
export declare type VariantValues = {
    [key: string]: string;
};
export declare type Variant = {
    variantValues: VariantValues;
    overrides: EscapeHatchProps;
};
export declare type ValidationResponse = {
    hasError: boolean;
    errorMessage?: string;
};
export declare type ValidationFunction<T> = (value: T, validationResponse: ValidationResponse) => ValidationResponse | Promise<ValidationResponse>;
export declare type InformeTasacionCreateFormInputValues = {
    fechaTasacion?: string;
    serviceDesk?: string;
    tipoTasacion?: string;
    pisos?: string;
    tipo?: string;
    entidadBancaria?: string;
    tipoTopologia?: string;
    ubicacion?: string;
    ubicacionTerreno?: string;
    propietario?: string;
    nombreSolicitante?: string;
    apellidoSolicitante?: string;
    condominio?: string;
    direccionInmueble?: string;
    bloque?: string;
    etapa?: string;
    manzana?: string;
    edificioNo?: string;
    tipoEdificio?: string;
    numeroTitulo?: string;
    constanciaVenta?: string;
    designacionCatastral?: string;
    libroNo?: string;
    folioNo?: string;
    parcela?: string;
    solar?: string;
    manzanaLegal?: string;
    dc?: string;
    localidad?: string;
    desarrollo?: string;
    tipologiaVecindario?: string;
    claseSocial?: string;
    aceras?: boolean;
    contenes?: boolean;
    callesAsfaltadas?: boolean;
    alcantarillado?: boolean;
    aguaPotable?: boolean;
    alumbradoElectrico?: boolean;
    telecomunicaciones?: boolean;
    transportePublico?: boolean;
    otrosInfraestructura?: boolean;
    area?: number;
    forma?: string;
    topografia?: string;
    edad?: string;
    nivelEdificacion?: number;
    descripcionInterior?: string;
    terminacionPisosInteriores?: string;
    terminacionPisosExteriores?: string;
    terminacionHuellas?: string;
    terminacionMuros?: string;
    terminacionRevestimiento?: string;
    terminacionPuertaPrincipal?: string;
    terminacionPuertasInteriores?: string;
    terminacionPuertasCloset?: string;
    terminacionGabinetes?: string;
    terminacionTopeCocina?: string;
    terminacionTecho?: string;
    terminacionCornisa?: string;
    terminacionPlafones?: string;
    terminacionVentanas?: string;
    terminacionPasamanos?: string;
    areaBasicoTerreno?: number;
    costoMetroBasicoTerreno?: number;
    areaBasicoConstruccion?: number;
    costoMetroBasicoConstruccion?: number;
    montoDepreciacion?: number;
    montoMejoras?: number;
    depreciacionMejoras?: number;
    valorInmueble?: number;
    comentario?: string;
};
export declare type InformeTasacionCreateFormValidationValues = {
    fechaTasacion?: ValidationFunction<string>;
    serviceDesk?: ValidationFunction<string>;
    tipoTasacion?: ValidationFunction<string>;
    pisos?: ValidationFunction<string>;
    tipo?: ValidationFunction<string>;
    entidadBancaria?: ValidationFunction<string>;
    tipoTopologia?: ValidationFunction<string>;
    ubicacion?: ValidationFunction<string>;
    ubicacionTerreno?: ValidationFunction<string>;
    propietario?: ValidationFunction<string>;
    nombreSolicitante?: ValidationFunction<string>;
    apellidoSolicitante?: ValidationFunction<string>;
    condominio?: ValidationFunction<string>;
    direccionInmueble?: ValidationFunction<string>;
    bloque?: ValidationFunction<string>;
    etapa?: ValidationFunction<string>;
    manzana?: ValidationFunction<string>;
    edificioNo?: ValidationFunction<string>;
    tipoEdificio?: ValidationFunction<string>;
    numeroTitulo?: ValidationFunction<string>;
    constanciaVenta?: ValidationFunction<string>;
    designacionCatastral?: ValidationFunction<string>;
    libroNo?: ValidationFunction<string>;
    folioNo?: ValidationFunction<string>;
    parcela?: ValidationFunction<string>;
    solar?: ValidationFunction<string>;
    manzanaLegal?: ValidationFunction<string>;
    dc?: ValidationFunction<string>;
    localidad?: ValidationFunction<string>;
    desarrollo?: ValidationFunction<string>;
    tipologiaVecindario?: ValidationFunction<string>;
    claseSocial?: ValidationFunction<string>;
    aceras?: ValidationFunction<boolean>;
    contenes?: ValidationFunction<boolean>;
    callesAsfaltadas?: ValidationFunction<boolean>;
    alcantarillado?: ValidationFunction<boolean>;
    aguaPotable?: ValidationFunction<boolean>;
    alumbradoElectrico?: ValidationFunction<boolean>;
    telecomunicaciones?: ValidationFunction<boolean>;
    transportePublico?: ValidationFunction<boolean>;
    otrosInfraestructura?: ValidationFunction<boolean>;
    area?: ValidationFunction<number>;
    forma?: ValidationFunction<string>;
    topografia?: ValidationFunction<string>;
    edad?: ValidationFunction<string>;
    nivelEdificacion?: ValidationFunction<number>;
    descripcionInterior?: ValidationFunction<string>;
    terminacionPisosInteriores?: ValidationFunction<string>;
    terminacionPisosExteriores?: ValidationFunction<string>;
    terminacionHuellas?: ValidationFunction<string>;
    terminacionMuros?: ValidationFunction<string>;
    terminacionRevestimiento?: ValidationFunction<string>;
    terminacionPuertaPrincipal?: ValidationFunction<string>;
    terminacionPuertasInteriores?: ValidationFunction<string>;
    terminacionPuertasCloset?: ValidationFunction<string>;
    terminacionGabinetes?: ValidationFunction<string>;
    terminacionTopeCocina?: ValidationFunction<string>;
    terminacionTecho?: ValidationFunction<string>;
    terminacionCornisa?: ValidationFunction<string>;
    terminacionPlafones?: ValidationFunction<string>;
    terminacionVentanas?: ValidationFunction<string>;
    terminacionPasamanos?: ValidationFunction<string>;
    areaBasicoTerreno?: ValidationFunction<number>;
    costoMetroBasicoTerreno?: ValidationFunction<number>;
    areaBasicoConstruccion?: ValidationFunction<number>;
    costoMetroBasicoConstruccion?: ValidationFunction<number>;
    montoDepreciacion?: ValidationFunction<number>;
    montoMejoras?: ValidationFunction<number>;
    depreciacionMejoras?: ValidationFunction<number>;
    valorInmueble?: ValidationFunction<number>;
    comentario?: ValidationFunction<string>;
};
export declare type PrimitiveOverrideProps<T> = Partial<T> & React.DOMAttributes<HTMLDivElement>;
export declare type InformeTasacionCreateFormOverridesProps = {
    InformeTasacionCreateFormGrid?: PrimitiveOverrideProps<GridProps>;
    fechaTasacion?: PrimitiveOverrideProps<TextFieldProps>;
    serviceDesk?: PrimitiveOverrideProps<TextFieldProps>;
    tipoTasacion?: PrimitiveOverrideProps<TextFieldProps>;
    pisos?: PrimitiveOverrideProps<TextFieldProps>;
    tipo?: PrimitiveOverrideProps<TextFieldProps>;
    entidadBancaria?: PrimitiveOverrideProps<TextFieldProps>;
    tipoTopologia?: PrimitiveOverrideProps<TextFieldProps>;
    ubicacion?: PrimitiveOverrideProps<TextFieldProps>;
    ubicacionTerreno?: PrimitiveOverrideProps<TextFieldProps>;
    propietario?: PrimitiveOverrideProps<TextFieldProps>;
    nombreSolicitante?: PrimitiveOverrideProps<TextFieldProps>;
    apellidoSolicitante?: PrimitiveOverrideProps<TextFieldProps>;
    condominio?: PrimitiveOverrideProps<TextFieldProps>;
    direccionInmueble?: PrimitiveOverrideProps<TextFieldProps>;
    bloque?: PrimitiveOverrideProps<TextFieldProps>;
    etapa?: PrimitiveOverrideProps<TextFieldProps>;
    manzana?: PrimitiveOverrideProps<TextFieldProps>;
    edificioNo?: PrimitiveOverrideProps<TextFieldProps>;
    tipoEdificio?: PrimitiveOverrideProps<TextFieldProps>;
    numeroTitulo?: PrimitiveOverrideProps<TextFieldProps>;
    constanciaVenta?: PrimitiveOverrideProps<TextFieldProps>;
    designacionCatastral?: PrimitiveOverrideProps<TextFieldProps>;
    libroNo?: PrimitiveOverrideProps<TextFieldProps>;
    folioNo?: PrimitiveOverrideProps<TextFieldProps>;
    parcela?: PrimitiveOverrideProps<TextFieldProps>;
    solar?: PrimitiveOverrideProps<TextFieldProps>;
    manzanaLegal?: PrimitiveOverrideProps<TextFieldProps>;
    dc?: PrimitiveOverrideProps<TextFieldProps>;
    localidad?: PrimitiveOverrideProps<TextFieldProps>;
    desarrollo?: PrimitiveOverrideProps<TextFieldProps>;
    tipologiaVecindario?: PrimitiveOverrideProps<TextFieldProps>;
    claseSocial?: PrimitiveOverrideProps<TextFieldProps>;
    aceras?: PrimitiveOverrideProps<SwitchFieldProps>;
    contenes?: PrimitiveOverrideProps<SwitchFieldProps>;
    callesAsfaltadas?: PrimitiveOverrideProps<SwitchFieldProps>;
    alcantarillado?: PrimitiveOverrideProps<SwitchFieldProps>;
    aguaPotable?: PrimitiveOverrideProps<SwitchFieldProps>;
    alumbradoElectrico?: PrimitiveOverrideProps<SwitchFieldProps>;
    telecomunicaciones?: PrimitiveOverrideProps<SwitchFieldProps>;
    transportePublico?: PrimitiveOverrideProps<SwitchFieldProps>;
    otrosInfraestructura?: PrimitiveOverrideProps<SwitchFieldProps>;
    area?: PrimitiveOverrideProps<TextFieldProps>;
    forma?: PrimitiveOverrideProps<TextFieldProps>;
    topografia?: PrimitiveOverrideProps<TextFieldProps>;
    edad?: PrimitiveOverrideProps<TextFieldProps>;
    nivelEdificacion?: PrimitiveOverrideProps<TextFieldProps>;
    descripcionInterior?: PrimitiveOverrideProps<TextFieldProps>;
    terminacionPisosInteriores?: PrimitiveOverrideProps<TextFieldProps>;
    terminacionPisosExteriores?: PrimitiveOverrideProps<TextFieldProps>;
    terminacionHuellas?: PrimitiveOverrideProps<TextFieldProps>;
    terminacionMuros?: PrimitiveOverrideProps<TextFieldProps>;
    terminacionRevestimiento?: PrimitiveOverrideProps<TextFieldProps>;
    terminacionPuertaPrincipal?: PrimitiveOverrideProps<TextFieldProps>;
    terminacionPuertasInteriores?: PrimitiveOverrideProps<TextFieldProps>;
    terminacionPuertasCloset?: PrimitiveOverrideProps<TextFieldProps>;
    terminacionGabinetes?: PrimitiveOverrideProps<TextFieldProps>;
    terminacionTopeCocina?: PrimitiveOverrideProps<TextFieldProps>;
    terminacionTecho?: PrimitiveOverrideProps<TextFieldProps>;
    terminacionCornisa?: PrimitiveOverrideProps<TextFieldProps>;
    terminacionPlafones?: PrimitiveOverrideProps<TextFieldProps>;
    terminacionVentanas?: PrimitiveOverrideProps<TextFieldProps>;
    terminacionPasamanos?: PrimitiveOverrideProps<TextFieldProps>;
    areaBasicoTerreno?: PrimitiveOverrideProps<TextFieldProps>;
    costoMetroBasicoTerreno?: PrimitiveOverrideProps<TextFieldProps>;
    areaBasicoConstruccion?: PrimitiveOverrideProps<TextFieldProps>;
    costoMetroBasicoConstruccion?: PrimitiveOverrideProps<TextFieldProps>;
    montoDepreciacion?: PrimitiveOverrideProps<TextFieldProps>;
    montoMejoras?: PrimitiveOverrideProps<TextFieldProps>;
    depreciacionMejoras?: PrimitiveOverrideProps<TextFieldProps>;
    valorInmueble?: PrimitiveOverrideProps<TextFieldProps>;
    comentario?: PrimitiveOverrideProps<TextFieldProps>;
} & EscapeHatchProps;
export declare type InformeTasacionCreateFormProps = React.PropsWithChildren<{
    overrides?: InformeTasacionCreateFormOverridesProps | undefined | null;
} & {
    clearOnSuccess?: boolean;
    onSubmit?: (fields: InformeTasacionCreateFormInputValues) => InformeTasacionCreateFormInputValues;
    onSuccess?: (fields: InformeTasacionCreateFormInputValues) => void;
    onError?: (fields: InformeTasacionCreateFormInputValues, errorMessage: string) => void;
    onChange?: (fields: InformeTasacionCreateFormInputValues) => InformeTasacionCreateFormInputValues;
    onValidate?: InformeTasacionCreateFormValidationValues;
} & React.CSSProperties>;
export default function InformeTasacionCreateForm(props: InformeTasacionCreateFormProps): React.ReactElement;
